ТЗ 13 готово
EduardM555/java-shareit pull request #1
Opened 2023-01-23 22:28 UTC by EduardM555

2023-01-24 15:28 UTC, andrew-larkin requested changes
Привет! Очень хорошо все реализовано, остается сделать небольшой рефакторинг и мы будем готовы двигаться дальше.

2023-01-24 15:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto addItem(@RequestHeader("X-Sharer-User-Id") Long userId,
ответы контроллера стоит оборачивать в ResponseEntity, т.к. он возвращает не только тело, но и http-статус. return ResponseEntity.ok().body( itemService.addItem(userId, itemDto)); - сделать по такому подобию для всех методов в контроллерах

2023-01-24 15:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
пока реализации не очень много, предлагаю познакомиться с библиотекой mapStruct - она позволить написать все эти методы в одну строку

2023-02-17 01:12 UTC, EduardM555 commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
Не успеваю, не смог найти достаточно материала для изучения/понимания

2023-02-17 19:24 UTC, merged