Add bookings
EduardM555/java-shareit pull request #2
Opened 2023-04-24 06:18 UTC by EduardM555

2023-04-24 15:50 UTC, andrew-larkin requested changes
Привет! Отлично, основной функционал выполнен корректно и по коду тоже все довольно чисто и прозрачно. Остается внести несколько правок и будем готовы двигаться дальше.

2023-04-24 15:50 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingAllDto saveBooking(@RequestHeader(value = "X-Sharer-User-Id",
в этом спринте давай добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(bookingService.save(...));
Для всех методов во всех контроллерах стоит его добавить

2023-04-24 15:50 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +//        log.warn("Создание booker " + booker);
закомментированный код удаляем

2023-04-24 15:50 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<List<UserDto>> getAll()  {
коммент для строки 40: тоже можем использовать ResponseEntity, указав у него тип Void

2023-04-24 15:50 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/UserDao.java
> +*/
ненужные классы удаляем

2023-04-24 15:50 UTC, andrew-larkin commented on src/main/resources/sql.txt
> +    id    bigint generated by default as identity
используются ли эти файлы?

2023-04-25 15:37 UTC, EduardM555 commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
С mapStruct не удалось мне разобраться. У нас в теории не было, в инете с инфой не разобрался. Не использую.

2023-04-25 15:54 UTC, EduardM555 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<List<UserDto>> getAll()  {
Не получилось сделать. Все методы по цепочки вплоть до репозитория нужно менять

2023-04-25 15:55 UTC, EduardM555 commented on src/main/resources/sql.txt
> +    id    bigint generated by default as identity
Удалил

2023-04-26 03:45 UTC, merged